name: Metrics
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    if: "github.repository == 'iamsainikhil/iamsainikhil'"
    steps:
      - name: 📅 Isocalendar plugin (full year)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ''
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugins_errors_fatal: ${{ github.repository == 'iamsainikhil/iamsainikhil' }}

      - name: 🌟 Stars plugin
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.stars.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ''
          plugin_stars: yes
          plugin_stars_limit: 2
          plugins_errors_fatal: ${{ github.repository == 'iamsainikhil/iamsainikhil' }}

      - name: 🧮 Traffic plugin
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.traffic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: repositories
          plugin_traffic: yes
          plugins_errors_fatal: ${{ github.repository == 'iamsainikhil/iamsainikhil' }}
